[package]
name = "railsearch"
version = "0.1.0"
authors = ["joe wehrli <wehrli@gatech.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
devtimer = "*"
